# fly.toml app configuration file generated for trading-fish-umami on 2023-05-26T17:30:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trading-fish-umami"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
image = "ghcr.io/umami-software/umami:postgresql-latest"

[env]
DISABLE_TELEMETRY = "1"
HASH_SALT = "pw)gaa8#dvew%yd^o4kwi2d1)%gxbu6-shdki*9%-u6h-mo!%g"
PRIMARY_REGION = "iad"
HOSTNAME = "0.0.0.0"

[[services]]
protocol = "tcp"
internal_port = 3000
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
restart_limit = 0
